### ISSUE TITLE
Gripper action returns result instantly (and incorrect)

### ISSUE THREAD

**Issue by mathijsdelangen** [RIVeR-Lab/wpi_jaco#19]
I have used the actionlib jaco_arm/fingers_controller/gripper to send a goal to the gripper. What I saw was that I received a result instantly when sending the goal. 
The result also contains the current width of the gripper and not the end width of the gripper (I think because the result is returned immediately). 

Next to that, I also received (reach_goal = true) when sending the gripper to an unreachable goal (say value 200).

The gripper should send the result only when the gripper has reached (or cannot reach) its goal.

**Comment by dekent** [comment]
The result position and reached_goal values are now reporting correctly, at the correct time.  Note that the stall condition is not reporting correctly, however, but I'll open a separate issue for that.
