### ISSUE TITLE
Firmware version / library version

### ISSUE THREAD

**Issue by davetcoleman** [RIVeR-Lab/wpi_jaco#23]
First, this repository looks awesome, thank you so much! The ROS wiki documentation is impressive. 

I'm trying to get up to speed on all the packages, however, and have a few questions:

- What version of the arm firmware are you guys using? It seems like the ``.so`` shared files in the /lib folder are out of date. To get the wpi_jaco_wrapper code to start without a segfault I have to manually copy and rename the latest library from https://github.com/Kinovarobotics/jaco-ros/tree/master/jaco_driver/lib/x86_64-linux-gnu
- Do I need to have the other repository built and running also? e.g. https://github.com/Kinovarobotics/jaco-ros
- Does this repo account for the new URDF-based TF publishing mode as described here? https://github.com/Kinovarobotics/jaco-ros#urdf-mode
- Which launch files are exactly need to get, say, the interactive marker demo working? I launch various things but it does not seem to reflect on the hand.

I understand if not all these features currently work or are up to date, I just need to know what I should and should not focus on. I really just want MoveIt! working with the arm.

Thanks!

**Comment by dekent** [comment]
Hi Dave,

We're using 5.0.6 for our arm, and yeah the shared files are definitely out of date.  I'll look into updating it ASAP, thanks for the info!

For your other two questions, our package is completely standalone from the Kinovarobotics/jaco-ros package.  We decided to implement our own package because we would have needed to make some fundamental changes to get the arm to do what we wanted, particularly with MoveIt!.  Because of this nothing from the jaco-ros package will work with our stuff.

Our latest commit has a MoveIt! config package that we've been able to use for basic motion planning for the arm, and  I'm open to any more discussion to get more MoveIt! functionality working with the jaco!

**Comment by davetcoleman** [comment]
Ah, we have the Jaco 2 with firmware 5.2.1.0022

I'm currently having issues with getting the shared objects (Kinova.API.CommLayerUbuntu Kinova.API.USBCommandLayerUbuntu) to link in catkin_tools without having to install it. Are you guys able to build the workspace without installing? I think the bug is having to do with the line

```
add_custom_command(TARGET Kinova.API.CommLayerUbuntu POST_BUILD COMMAND cp ${JACO_COMM_LIB} ${CMAKE_LIBRARY_OUTPUT_DIRECTORY}/)        
```

But when I change the last argument to ``${CATKIN_PACKAGE_LIB_DESTINATION}`` it still does not work. Not sure what else to try...

**Comment by dekent** [comment]
Yeah we can build the package without installing.  Did you try copying the new Kinova.API.CommLayerUbuntu.so and Kinova.API.USBCommandLayerUbuntu.so files before building?

**Comment by davetcoleman** [comment]
Ah, if I manually copy ``libKinova.API.CommLayerUbuntu.so`` and the USB on into the ``/devel/lib/`` folder it works. But, most likely because I'm using the new build tool [catkin_tools](catkin-tools.readthedocs.org) the old CMake hooks to copy this no longer work. Still not sure what to do to permanently fix this.

**Comment by jbohren** [comment]
@davetcoleman Just get rid of `EXCLUDE_FROM_ALL` on lines 32 and #36 and it will work with `catkin build`. Since nobody depends on these targets in the isolated build context, and since they're excluded from the `all` target, they're just not being copied.

**Comment by davetcoleman** [comment]
@dekent things build now, but joint_states that are being published are wrong. I believe in the latest firmware / Jaco version you need some extra math, as found in their driver: 
https://github.com/Kinovarobotics/jaco-ros/blob/master/jaco_driver/src/jaco_arm.cpp#L335

I attempted to port their latest drivers to this repo, but it turned out to be a lot more involved than I thought so I am putting it aside for now in favor of trying https://github.com/peci1/jaco-ros/commit/3c221a05c2d82713de026e85b861ce9ed96a13d9

Thanks again for creating all of this, I understand it can be frustrating when the vendor's API changes and I don't blame you guys at all!

**Comment by dekent** [comment]
.so files updated.  Good luck with the new Jaco!

**Comment by davetcoleman** [comment]
Awesome!

By no means am I asking you to put time into this, but fyi in Jaco 2 there are a number of changes in how joint positions are done so for now I'm sticking with their code.
