### ISSUE TITLE
Home Service on Start necessary?

### ISSUE THREAD

**Issue by raphimulator** [RIVeR-Lab/wpi_jaco#35]
Hi,
when launching arm.launch, the jaco_arm_trajectory_node is started and it calls the home-service.
This might not be a common problem, but when Mico is build on top of our robot, homing can cause dangerous collisions.

Is it possible to initialize without homing? Or can I make homing somehow optional, without modifying too much of your code?

**Comment by dekent** [comment]
Unfortunately, homing is part of kinova's startup procedure for the arm (calibration probably).  You could check with Kinova about alternatives, or if you can set a different home position, but in my experience it has a required, preset home position.

**Comment by mathijsdelangen** [comment]
Hi,

I would like to comment on this issue. I have had extended conversations with the ROS support of Kinova and I have been told that homing is not required anymore with the latest firmware. Hence, you can disable it in the software if needed.

I have also had some problems with the switching between angular and cartesian control. It seems that the Kinova API sometimes deadlocks - or stays in the angular control - even when trying to switch it back to cartesian control. For us, this could only be solved by homing, but this is another issue which should be fixed sometime in the future.

For this latest issue, someone should contact ROS support of Kinova. This can be done via ros@kinovarobotics.com.

**Comment by dekent** [comment]
Oh, that's good to hear!  I'll add a flag to the launch file to make homing optional.  We've had safety issues with the home as well, so I'd like to bypass it.

**Comment by dekent** [comment]
Parameter's added, the arm will still home on initialization by default, but if you don't want it to then launch the arm with:

roslaunch wpi_jaco_wrapper arm.launch home_arm_on_init:=false
