### ISSUE TITLE
Could not initialize Kinova API

### ISSUE THREAD

**Issue by kural007** [RIVeR-Lab/wpi_jaco#39]
Hello,
I want a smooth arm motion while following a trajectory points. I am using the wpi_jaco_wrapper package. In this i want to pass the 6 joint angles of n points as paratemeters to the smooth_arm_motion function in the jaco_arm_trajectory_node. I have the parameter values in a text file. I have written the following c++ code in a new package called test in the same work space:

#include<iostream>
#include<stdlib.h>
#include<fstream>
#include<string.h>
#include<sstream>
#include<time.h>
#include<vector>
#include<ros/ros.h>
#include "control_msgs/FollowJointTrajectoryGoal.h"
#include "/opt/ros/hydro/include/trajectory_msgs/JointTrajectoryPoint.h"
#include "/opt/ros/hydro/include/trajectory_msgs/JointTrajectory.h"
#include </home/administrator/catkin_ws/src/wpi_jaco/wpi_jaco_wrapper/include/wpi_jaco_wrapper/jaco_arm_trajectory_node.h>
using namespace std;

void letswait(int);

int main(int argc, char **argv)
{
	
	char filename[100];
	float temp;
	int row=0;
	stringstream rosrun;
	
	//find out number of rows
	strcpy(filename,argv[1]);
	ifstream myfile (filename);
	if(myfile.is_open())
	{
		while(!myfile.eof())
		{
			myfile>>temp;
			row++;		
		}
	}	
	row--;
	row=row/6;
	
	//refresh the file read
	myfile.clear();
	myfile.seekg(0,myfile.beg);
	
	//create dynamic table
	double **table; 
	table = new double* [row];
	for(int i=0;i<row;i++)
	table[i] = new double [6];
	
	//read the file into table

	control_msgs::FollowJointTrajectoryGoal *goalPtr = new control_msgs::FollowJointTrajectoryGoal();
	
	
		for(int i=0;i<row;i++)
			{
				for(int j=0;j<6;j++)
				{
					myfile>>table[i][j];
						
				}
			}
			
	for (int k=0;k<4;k++)
	{
		vector<trajectory_msgs::JointTrajectoryPoint> points(row);
		for(int i=0;i<row;i++)
		{
			vector<double> positions(6);
			for(int j=0;j<6;j++)
			{
				positions[j] = table[i][j];
			}
			points[i].positions = positions;

		}
		goalPtr->trajectory.points = points;
		//cout<<goalPtr.trajectory.points[2].positions[2];
		
		//const control_msgs::FollowJointTrajectoryGoalConstPtr *goal = goalPtr;
		//*goalPtr;
		
		ros::init(argc, argv, "jaco_arm_trajectory_node");
		ros::NodeHandle nh;
		ros::NodeHandle pnh("~");
		
		jaco::JacoArmTrajectoryController ctrl(nh, pnh);
		ctrl.execute_smooth_trajectory((control_msgs::FollowJointTrajectoryGoalConstPtr&)*goalPtr);

	}
		
	//free memory
	delete[] table; 
	//delete goalPtr;	
	
	
	return 0; 
}

void letswait(int secs){
	clock_t end;
	end=clock()+secs*CLOCKS_PER_SEC;
	while(clock()<end);
}

i have also attached my cmake file for the package here
[CMakeLists.txt](https://github.com/RIVeR-Lab/wpi_jaco/files/38440/CMakeLists.txt).

I did the roslaunch first for the wpi_jaco_wrapper and it was successful with homing and everything, and i opened a new terminal and tried to rosrun test testk , but it comes up as it could not find the kinova api.

PLEASE TELL ME WHAT MISTAKE I HAVE IN MY C++ PROGRAM, OR WHAT I HAVE MADE MISTAKE IN THE CMAKE LIST?, I THINK SOME LINKING ERROR IS THE REASON!!..

AUTHORS, PLEASE PROVIDE ANY SIMPLE EXAMPLE OF HOW TO USE THE PACKAGE, HOW TO USE THE SMOOTH ARM MOTION BY SENDING THE VALUES WHICH I HAVE IN A TEXT FILE,  PLEASE GIVE A STEP BY STEP INSTRUCTION OR PLEASE ADD MORE IN THE DOCUMENTATION SO THAT SOME BEGINERS LIKE ME WILL BE ABLE TO GET IT BETTER. I HAVE EVEN TRIED CONTACTING THE WPI DEPARTMENT TO GET IN TOUCH WITH THE AUTHORS, BUT IN VAIN. PLEASE PROVIDE YOUR EMAIL ID IF ITS POSSIBLE. THIS PROJECT MEANS A LOT TO MY RESEARCH, SO PLEASE HELP ME OUT

KURAL
karutse@ncsu.edu

**Comment by dekent** [comment]
Hello Kural,

The wpi_jaco_wrapper package has a trajectory follower set up as a ROS actionlib server.  You're attempting to call an actionlib callback method directly in your C++ code, which will not work.  You instead need to create an actionlib client that connects to the trajectory actionlib server that you want to use.  For detailed instructions on how to do this, check out the actionlib page of the ROS wiki, which also has a complete set of tutorials: http://wiki.ros.org/actionlib

**Comment by kural007** [comment]
#include<iostream>
#include<stdlib.h>
#include<fstream>
#include<string.h>
#include<sstream>
#include<time.h>
#include<vector>
#include<ros/ros.h>
#include "control_msgs/FollowJointTrajectoryGoal.h"
#include "/opt/ros/hydro/include/trajectory_msgs/JointTrajectoryPoint.h"
#include "/opt/ros/hydro/include/trajectory_msgs/JointTrajectory.h"
#include </home/administrator/catkin_ws/src/wpi_jaco/wpi_jaco_wrapper/include/wpi_jaco_wrapper/jaco_arm_trajectory_node.h>
#include <actionlib/client/simple_action_client.h>
using namespace std;

typedef actionlib::SimpleActionClient<JacoArmTrajectoryController::execute_smooth_trajectory> TrajClient;

void letswait(int);

int main(int argc, char **argv)
{
	
	char filename[100];
	float temp;
	int row=0;
	stringstream rosrun;
	
	//find out number of rows
	strcpy(filename,argv[1]);
	ifstream myfile (filename);
	if(myfile.is_open())
	{
		while(!myfile.eof())
		{
			myfile>>temp;
			row++;		
		}
	}	
	row--;
	row=row/6;
	
	//refresh the file read
	myfile.clear();
	myfile.seekg(0,myfile.beg);
	
	//create dynamic table
	double **table; 
	table = new double* [row];
	for(int i=0;i<row;i++)
	table[i] = new double [6];
	
	//read the file into table
	
	TrajClient* traj_client_;
	traj_client_ = new TrajClient("jaco_arm_trajectory_node/smooth_trajectory_server_", true);
	
	control_msgs::FollowJointTrajectoryGoal goal = new control_msgs::FollowJointTrajectoryGoal();
	
	
	
	
		for(int i=0;i<row;i++)
			{
				for(int j=0;j<6;j++)
				{
					myfile>>table[i][j];
						
				}
			}
			
	for (int k=0;k<4;k++)
	{
		vector<trajectory_msgs::JointTrajectoryPoint> points(row);
		for(int i=0;i<row;i++)
		{
			vector<double> positions(6);
			for(int j=0;j<6;j++)
			{
				positions[j] = table[i][j];
			}
			points[i].positions = positions;

		}
		goal.trajectory.points = points;
		
		
		ros::init(argc, argv, "jaco_arm_trajectory_node");
		ros::NodeHandle nh;
		ros::NodeHandle pnh("~");
		
		jaco::JacoArmTrajectoryController ctrl(nh, pnh);
		ctrl.execute_smooth_trajectory(goal);

	}
		/
	delete[] table; 
		
	
	
	return 0; 
}


void letswait(int secs){
	clock_t end;
	end=clock()+secs*CLOCKS_PER_SEC;
	while(clock()<end);
}


I have tried to call the function through the actionlib client. I have initialized the client and connected to the server but I am not able to call the function. Please help.

Thanking You
KURAL
karutse@ncsu.edu

**Comment by dekent** [comment]
You need to send the goal through the connected action client, rather than calling the function.  I recommend going through and running at least the beginner tutorials here http://wiki.ros.org/actionlib/Tutorials before you try to use actionlib.
