### ISSUE TITLE
How to use MICO_MOVEIT_CONFIG 

### ISSUE THREAD

**Issue by patzaa** [RIVeR-Lab/wpi_jaco#40]
Hello everyone, 

I’m using the Kinova Arm Mico. I have installed and compiled the wpi_jaco Package. Now I want to test the mico_moveit_config. 

so I'm launching 

`roslaunch wpi_jaco_wrapper arm.launch`
`roslaunch mico_description mico_description.launch`
finally  
`roslaunch mico_moveit_config demo.launch`

rviz comes up and the arm its moving in rviz when I use the remote. The join state Publisher GUI also comes up.

But now my challenges: 

**fist:** 

when I'm trying to operate the join state publisher GUI to move the several joints the faders immediately moving back to the origin position without any effects to the arm??

**second:**

I press the interactive bottom in the left corner there is no ball tool coming up where I could move the arm via mouse. 

**third:** 

Got a Global Status Error: Fixed Frame Table dose not exist. 

-->**my target is grasp a bottle an and put it on a tray using MoveIt**

if you need any further pictures pleas let me know

**Thank you very much guys!**

**Comment by dekent** [comment]
Hello patzaa,

1) The joint state publisher is used more for simulation, to set a joint state if you don't have a physical arm connected to read the joint states from.  Since you have a running arm connected, they're getting reset immediately because moveit is reading the joint states from the arm instead.  If you want to physically move the arm you'll have to use something like the teleop package.

2 and 3) Both of these are happening because the global fixed frame was incorrectly set in the rviz window.  I updated it so that it should be fixed. The interactive marker for moving the arm is displaying for me now, so pull the latest version of the code, try it again, and let me know if there are any more problems.

**Comment by patzaa** [comment]
Hello dekent, 

thank you for your chances! 
I updated the package. When I now launch the arm.launch and the moveit demo.launch, I now got the interactive maker for moving the arm. Anyway there goes something wrong with the initialization of the virtual robo model in rviz because now just looks like one whole peace of joints and material. Nothing is actually moving when I use the remote. Maybe I did something wrong but i tried several times now.

**Comment by dekent** [comment]
Can you post a screenshot of what rviz looks like?

**Comment by patzaa** [comment]
this is how rviz looks like: 

![moveit demo](https://cloud.githubusercontent.com/assets/15317628/11676343/a7ad71ce-9e6c-11e5-89ef-a60ef853ece4.png)

the planing and execution fails: 

![planing fail](https://cloud.githubusercontent.com/assets/15317628/11676398/d8dfbe82-9e6c-11e5-9334-737699af3fc9.png)


finally the demo.launch output: 

![the demo launch](https://cloud.githubusercontent.com/assets/15317628/11676428/0faf8992-9e6d-11e5-98fb-9366dae2fb14.png)

if you need any further screenshots just let me know

**Comment by dekent** [comment]
It looks like the demo.launch file is assuming you don't have a robot connected, so it's setting up its own joint state publisher which is overriding the mico's joint states.  You'll want to create your own launch file that starts everything correctly according to your physical setup, which will involve taking out these lines from the demo.launch file, and possibly some other configuration depending on your environment:
```
<!-- We do not have a robot connected, so publish fake joint states -->
  <node name="joint_state_publisher" pkg="joint_state_publisher" type="joint_state_publisher">
    <param name="/use_gui" value="true"/> 
    <rosparam param="/source_list">[/move_group/fake_controller_joint_states]</rosparam>
  </node>
  
  <!-- Given the published joint states, publish tf for the robot links -->
  <node name="robot_state_publisher" pkg="robot_state_publisher" type="robot_state_publisher" respawn="true" output="screen" />
```
For additional configuration, take a look at the arguments in the move_group.launch file.  If you want to use any sensors as well (such as a kinect), take a look at the sensor_manager.launch file, which is currently set up with an example configuration for a point cloud sensor.
