### ISSUE TITLE
join and robo_state_publisher not working on real robot?

### ISSUE THREAD

**Issue by patzaa** [RIVeR-Lab/wpi_jaco#41]
Hello everybody 

I'm using the mico Arm. 
When I'm launching the arm.launch and initialise the robot. 
and launching the mico_description.launch to setup the join_state_publisher and robo_state_publisher and want to view the result in rviz it looks like this and not like the real home position?

![rviz](https://cloud.githubusercontent.com/assets/15317628/11804652/5c5b6d38-a340-11e5-840c-4bfd1420e849.png)

and not like the real home position? 

Thank you very much

**Comment by dekent** [comment]
Once you have everything running, is anything being published on the topic /mico_arm/joint_states?  If there are messages being published, post a screenshot or a log of a couple of them.

If there are no messages on that topic, check if anything is being published on /jaco_arm/joint_states instead, let me know if this is the case, and we can continue debugging from there.

**Comment by patzaa** [comment]
You are right there is nothing published on the topic mico_arm/joint_states all the joint states got published on /jaco_arm/joint_states 
the value of finger three is constantly zero.

**Comment by dekent** [comment]
It sounds like you're launching the arm with the jaco parameters instead of the mico parameters.  When using arm.launch, make sure you're using the syntax:

`roslaunch wpi_jaco_wrapper arm.launch arm_name:=mico`

This should get everything publishing on the correct topics.

**Comment by dekent** [comment]
Closed for inactivity.
