### ISSUE TITLE
Gripper Action Server isn't responding

### ISSUE THREAD

**Issue by ksatyaki** [RIVeR-Lab/wpi_jaco#48]
Hello, 

When I do, 

```
    control_msgs::GripperCommandGoal gripper_goal;
    gripper_goal.command.position = 65.0;
    gripper_client_.waitForServer();
    gripper_client_.sendGoal(gripper_goal);
    ROS_INFO("Sending gripper goal...");
    gripper_client_.waitForResult();
    ROS_INFO("OK");
```

waitForResult() doesn't return and the gripper doesn't work. I can connect to the server successfully. And the status topic reports that the goal has been accepted by the action server. Could you please help me solve this issue?

I use the indigo-devel version from the ROS repositories.
The arm is Jaco2.

Thanks
Chittaranjan

**Comment by dekent** [comment]
Hello Chittaranjan,

I'm not sure why it's not working for you.  The gripper has no movement at all?

It's difficult for me to debug on my end, because my lab doesn't have a JACO2 with a Kinova gripper.  This may be a problem with the JACO2 that I'm not aware of.

Let's start with your parameters.  How are you launching the node and what are all of your parameters set to?  Are you using the default jaco2.yaml config file or did you change anything?

**Comment by ksatyaki** [comment]
First of all, thank you for the prompt reply!

I just realized that I hadn't changed the arm_name argument in the default arm.launch ... Now that I have changed it, I see that the the names of the joints published in joint_states are different ... "_elbow_joint, shoulder_joint, etc instead of joint_1, joint_2 etc. Trying to figure out where I could change this.

**Comment by ksatyaki** [comment]
I changed the relevant lines in "jaco_arm_trajectory_node.cpp" to get the joint names right. However I still do not have any finger movement. 

Here are the launch files I use.

### arm.launch

```
<launch>
  <arg name="arm_name" default="jaco2" />
  <arg name="home_arm_on_init" default="false" />
  <arg name="kinova_gripper" default="true" />

  <rosparam command="load" file="$(find wpi_jaco_wrapper)/config/$(arg arm_name).yaml"/>

  <node name="jaco_arm_trajectory_node" pkg="wpi_jaco_wrapper" type="jaco_arm_trajectory_node" output="screen">
    <param name="home_arm_on_init" value="$(arg home_arm_on_init)" />
    <param name="kinova_gripper" value="$(arg kinova_gripper)" />
  </node>

  <!-- We can remove this node for now. We have our own manipulation stuff. -->
  <!--  node name="jaco_manipulation" pkg="wpi_jaco_wrapper" type="jaco_manipulation" output="screen">
    <param name="kinova_gripper" value="$(arg kinova_gripper)" />
  </node -->

  <node name="jaco_conversions" pkg="wpi_jaco_wrapper" type="jaco_conversions"/>
  <node name="jaco_kinematics" pkg="wpi_jaco_wrapper" type="jaco_kinematics"/>

</launch>

```

### jaco_moveit.launch

```
<launch>

  <!-- By default, we do not start a database (it can be large) -->
  <arg name="db" default="false" />

  <!-- Do we want to start rviz. By default no -->
  <arg name="viz" default="false" />

  <!-- By default, we are not in debug mode -->
  <arg name="debug" default="false" />

  <!-- Load the URDF, SRDF and other .yaml configuration files on the param server -->
  <include file="$(find jaco_moveit_config)/launch/planning_context.launch">
    <arg name="load_robot_description" value="true"/>
  </include>

  <!-- Merge the joint states -->
  <node name="joint_state_publisher" pkg="joint_state_publisher" type="joint_state_publisher">
    <param name="/use_gui" value="false"/> 
    <rosparam param="/source_list">[jaco_arm/joint_states]</rosparam>
  </node>

  <!-- Given the published joint states, publish tf for the robot links -->
  <node name="robot_state_publisher" pkg="robot_state_publisher" type="robot_state_publisher" respawn="true" output="screen" />

  <!-- Run the main MoveIt executable with trajectory execution -->
  <include file="$(find jaco_moveit_config)/launch/move_group.launch">
    <arg name="allow_trajectory_execution" value="true"/>  
    <arg name="fake_execution" value="false"/>
    <arg name="info" value="true"/>
    <arg name="debug" value="$(arg debug)"/>
  </include>

  <!-- Run Rviz and load the default config to see the state of the move_group node -->
  <include file="$(find jaco_moveit_config)/launch/moveit_rviz.launch" if="$(arg viz)">
    <arg name="config" value="true"/>
    <arg name="debug" value="$(arg debug)"/>
  </include>

  <!-- If database loading was enabled, start mongodb as well -->
  <include file="$(find jaco_moveit_config)/launch/default_warehouse_db.launch" if="$(arg db)"/>

</launch>
```

### manipulation.launch

```
<?xml version="1.0"?>

<launch>

  <arg name="vizz" default="false" />

  <!-- Launches the driver for the arm  -->
  <!--  include file="$(find wpi_jaco_wrapper)/launch/arm.launch" / -->
  <include file="$(find manipulation_launch)/launch/arm.launch" />

  <!-- Launches the moveit config for the arm -->
  <include file="$(find manipulation_launch)/launch/jaco_moveit.launch">
    <arg name="viz" value="$(arg vizz)" />
  </include>

  <!-- Launches jaco_manipulation node -->
  <node name="manipulation_server" type="manipulation_server" pkg="jaco_manipulation" />

  <!-- Launches the pick_up_action server -->
  <node name="pick_up_action_server" type="pick_up_action_server" pkg="pick_up_action" />

  <!--  Static transform publisher -->
  <node pkg="tf" type="static_transform_publisher" name="base_link_broadcaster" args="-0.25 -0.20 0 -1.5708 0 0 root base_link 50" />

</launch>
```

All the nodes are from the ros-indigo apt repositories (except the jaco_arm_trajectory_node since I had to install it separately - to adjust the joint_names for jaco2)...

### Update:

#### This doesn't work as well:

```
rostopic pub /jaco_arm/angular_cmd wpi_jaco_msgs/AngularCommand "position: true
armCommand: false
fingerCommand: true
repeat: true
joints: [0]
fingers: [0, 0, 0]" 
```

**Comment by dekent** [comment]
Yeah, it looks like everything's set up correctly.  Since the angular command isn't working either, I think this is either a hardware error or a something in the Kinova API changed between the JACO1 manipulator and the JACO2 manipulator.  Can you verify that you can control the gripper using something like jacosoft or one of Kinova's sample test programs?

**Comment by ksatyaki** [comment]
I tried the sample test program called "Example_AngularControl" and this seems to work (the fingers move). 

EDIT: It doesn't work actually. It's not clear how I can send commands to the fingers...

**Comment by dekent** [comment]
Ok.  Until you can verify it works with the Kinova API, I can't help in debugging the wpi_jaco package with your setup, since it directly uses the Kinova API.

Good luck, and feel free to reopen this if you can control the fingers but it still doesn't work with the wpi_jaco package!

**Comment by ksatyaki** [comment]
I have verified that the gripper works with the API. Apparently, the gripper values should be between 0 (open) and 7000 (closed) or something. This is what the control center shows too (I don't understand the units). 

I didn't change any code from your action servers. I simply tested it using a callback and it seems to work. 

I will post the code here for now.

`
void JacoArmTrajectoryController::fingersCallback(const std_msgs::Float32::ConstPtr& msg) {
    openCloseFingers(msg->data);
}

void JacoArmTrajectoryController::openCloseFingers(float value) {

```
cout << "Initializing the fingers" << endl;
//InitFingers();

EraseAllTrajectories();

SetAngularControl();

FingersPosition fingers;
fingers.InitStruct();
memset(&fingers, 0, sizeof(fingers));

fingers.Finger1 = value;
fingers.Finger2 = value;
fingers.Finger3 = value;


TrajectoryPoint jaco_position;
jaco_position.InitStruct();
memset(&jaco_position, 0, sizeof(jaco_position));

// Initialize Cartesian control of the fingers
jaco_position.Position.HandMode = POSITION_MODE;
jaco_position.Position.Type = ANGULAR_POSITION;
jaco_position.Position.Fingers = fingers;
jaco_position.Position.Delay = 0.0;
jaco_position.LimitationsActive = 0;

AngularPosition jaco_angles;
memset(&jaco_angles, 0, sizeof(jaco_angles));  // zero structure

GetAngularPosition(jaco_angles);
jaco_position.Position.Actuators = jaco_angles.Actuators;

// When loading a cartesian position for the fingers, values are required for the arm joints
// as well or the arm goes nuts.  Grab the current position and feed it back to the arm.
CartesianPosition pose;
GetCartesianPosition(pose);
jaco_position.Position.CartesianPosition = pose.Coordinates;

SendAdvanceTrajectory(jaco_position);
```

}
`

Parts of this code are from the kinova_ros drivers (https://github.com/Kinovarobotics/kinova-ros).
